### ISSUE TITLE
WiFi: ESP Access point connection mythology 

### ISSUE THREAD

**Issue by genestealer** [CRAPproject/CRAPnode-firmware#1]
Idea: Method for Wi-Fi connection
1. ESP tries to connect to last known/programmed wifi access point.
2. If after X number of connection attempts and after xx time stop attempting.
3.  Then Put ESP in wifi host access point to allow direct connection to configure ESP.

**Comment by scotty3785** [comment]
9 years and you didn't bother to implement it! :p
Crapnode indeed!
